name: Add model documentation

on:
  push:
    branches:
      - main

jobs:
  add-model-readme:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Update readme
        run: |
          install.packages("broom", "knitr", "ggplot2", "gt", "gtsummary")
          source("process_file.R")
        shell: sudo Rscript {0}
        env: 
          README_EXECUTABLE: R/example.R # Change this to the location of your modeling script
          COEF_PLOT: FALSE # Whether to plot model coefficients alongside each other in README

      - name: Commit and push changes
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add .
          git commit -m "Update documentation" || echo "No changes to commit"
          git pull --ff-only
          git push origin