name: Add model documentation

on:
  push:
    branches:
      - main

jobs:
  add-model-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2

      - name: Update readme
        run: source("model_readme/process_file.R")
        shell: Rscript {0}
        env: 
          README_EXECUTABLE: R/example.R # Change this to the location of your modeling script
          COEF_PLOT: FALSE # Whether to plot model coefficients alongside each other in README

      - name: Commit & Push readme changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}